inherit_mode:
  merge:
    - Include

plugins:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  SuggestExtensions: true
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'node_modules/**/*'
    - 'test/dummy/db/schema.rb'
    - 'vendor/**/*'

# https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Bundler/OrderedGems
Bundler/OrderedGems:
  Exclude:
    - 'gemfiles/*.gemfile'

# https://docs.rubocop.org/rubocop/latest/cops_metrics.html#metricsabcsize
Metrics/AbcSize:
  Exclude:
    - 'lib/undercarriage/controllers/restful/actions/*_concern.rb'

# https://docs.rubocop.org/rubocop/cops_metrics.html#metricsblocklength
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

# https://docs.rubocop.org/rubocop/latest/cops_metrics.html#metricsmethodlength
Metrics/MethodLength:
  Exclude:
    - 'test/dummy/db/migrate/*.rb'

# https://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/ExampleLength
RSpec/ExampleLength:
  Exclude:
    - 'spec/**/*'

# https://rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/MultipleExpectations
RSpec/MultipleExpectations:
  Exclude:
    - 'spec/lib/undercarriage/controllers/restful/**/*_concern_spec.rb'
    - 'spec/models/*.rb'
    - 'spec/requests/**/*.rb'

# https://docs.rubocop.org/rubocop-rspec_rails/latest/cops_rspecrails.html#rspecrailsinferredspectype
RSpecRails/InferredSpecType:
  Exclude:
    - 'spec/models/*_spec.rb'
    - 'spec/requests/**/*_spec.rb'

# https://docs.rubocop.org/rubocop/cops_style.html#styledocumentation
Style/Documentation:
  Enabled: true

# https://docs.rubocop.org/rubocop/cops_style.html#stylefrozenstringliteralcomment
Style/FrozenStringLiteralComment:
  Exclude:
    - 'bin/**/*'
    - 'gemfiles/*.gemfile'
    - 'test/dummy/bin/**/*'

# https://docs.rubocop.org/rubocop/cops_style.html#stylestringliterals
Style/StringLiterals:
  EnforcedStyle: double_quotes
  Exclude:
    - 'gemfiles/*.gemfile'

# https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/HashSyntax
Style/HashSyntax:
  Exclude:
    - 'gemfiles/*.gemfile'
