inherit_mode:
  merge:
    - Include

plugins:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  SuggestExtensions: true
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'test/dummy/db/schema.rb'
    - 'vendor/**/*'

# https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Bundler/OrderedGems
Bundler/OrderedGems:
  Exclude:
    - 'gemfiles/*.gemfile'

# https://docs.rubocop.org/rubocop/latest/cops_metrics.html#metricsmethodlength
Metrics/MethodLength:
  Exclude:
    - 'test/dummy/db/migrate/*.rb'

# https://docs.rubocop.org/rubocop-rspec_rails/latest/cops_rspecrails.html#rspecrailsinferredspectype
RSpecRails/InferredSpecType:
  Exclude:
    - 'spec/requests/**/*_spec.rb'

# https://docs.rubocop.org/rubocop/cops_style.html#styledocumentation
Style/Documentation:
  Enabled: true

# https://docs.rubocop.org/rubocop/cops_style.html#stylefrozenstringliteralcomment
Style/FrozenStringLiteralComment:
  Exclude:
    - 'bin/**/*'
    - 'gemfiles/*.gemfile'
    - 'test/dummy/bin/**/*'

# https://docs.rubocop.org/rubocop/cops_style.html#stylestringliterals
Style/StringLiterals:
  EnforcedStyle: double_quotes

# https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/HashSyntax
Style/HashSyntax:
  Exclude:
    - 'gemfiles/*.gemfile'
